// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsGmzD7mFZq9ixB_Yn2KyRxc2jHQwRCjo',
    appId: '1:128655028422:android:882b28ab36566424aae7c7',
    messagingSenderId: '128655028422',
    projectId: 'as-dsm-mathias',
    storageBucket: 'as-dsm-mathias.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMMAp0FW8oMpmaKpg_eV69djdbGNY0-I',
    appId: '1:735675722674:ios:228192d703062c44be92ab',
    messagingSenderId: '735675722674',
    projectId: 'as-dsm-firebase',
    storageBucket: 'as-dsm-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ap2Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmMMAp0FW8oMpmaKpg_eV69djdbGNY0-I',
    appId: '1:735675722674:ios:228192d703062c44be92ab',
    messagingSenderId: '735675722674',
    projectId: 'as-dsm-firebase',
    storageBucket: 'as-dsm-firebase.firebasestorage.app',
    iosBundleId: 'com.example.ap2Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5t5_PfdfTdSBJ3qZ5wzacKJu3Rr-J8RY',
    appId: '1:735675722674:web:debbc860e7b43427be92ab',
    messagingSenderId: '735675722674',
    projectId: 'as-dsm-firebase',
    authDomain: 'as-dsm-firebase.firebaseapp.com',
    storageBucket: 'as-dsm-firebase.firebasestorage.app',
  );

}